version: "3"

name: one_datanode

services:
  namenode:
    build: 
      context: ./namenode
    image: docker.io/library/my_hadoop_3.2.4:namenode 
    container_name: namenode
    working_dir: /root
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  datanode1:
    build: 
      context: ./datanode
    image: docker.io/library/my_hadoop_3.2.4:datanode 
    container_name: datanode1
    restart: always
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network
  
  resourcemanager:
    build: 
      context: ./resourcemanager
    image: docker.io/library/my_hadoop_3.2.4:resourcemanager 
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  nodemanager1:
    build: 
      context: ./nodemanager
    image: docker.io/library/my_hadoop_3.2.4:nodemanager 
    container_name: nodemanager1
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network
  
  historyserver:
    build: 
      context: ./historyserver
    image: docker.io/library/my_hadoop_3.2.4:historyserver 
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 resourcemanager:8088"
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network
  
networks:
  hadoop_network:
    driver: bridge

# volumes:
#   hadoop_namenode:
#   hadoop_datanode:
#   hadoop_historyserver:
